
global SENSOR_LIST
global SENSOR_GPIO
global SENSOR_TRANS_DRIVE

global WIFI_SSID
global WIFI_PASS
global WIFI_CONNECTED

global ADA_USERNAME
global ADA_KEY
global ADA_TOPICS_LIST

global DEVICE_ID
global SLEEP_TIMER_SEC